dir = pwd()
push!(LOAD_PATH, dir * "/ChiefOffice")
push!(LOAD_PATH, dir * "/Conds")
push!(LOAD_PATH,  dir * "/Contracts_CFG")
push!(LOAD_PATH,  dir * "/DataRoutines")
push!(LOAD_PATH,  dir * "/IPlot")
push!(LOAD_PATH,  dir * "/Portfolio")
push!(LOAD_PATH,  dir * "/Schemes")
push!(LOAD_PATH, dir * "/Seek")
push!(LOAD_PATH,  dir * "/StratPort")
push!(LOAD_PATH,  dir * "/StratSys")
push!(LOAD_PATH,  dir * "/SeekUtils")
push!(LOAD_PATH,  dir * "/Technicals")
